// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: bots/v1/whois_bot.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhoisBotService_ProbeHost_FullMethodName = "/whois.v1.WhoisBotService/ProbeHost"
)

// WhoisBotServiceClient is the client API for WhoisBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhoisBotServiceClient interface {
	// ProbeHost immediately starts whois query (manual use).
	// production use is limited due to system passing new tasks through redis queues
	ProbeHost(ctx context.Context, in *ProbeOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WhoisInfo], error)
}

type whoisBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhoisBotServiceClient(cc grpc.ClientConnInterface) WhoisBotServiceClient {
	return &whoisBotServiceClient{cc}
}

func (c *whoisBotServiceClient) ProbeHost(ctx context.Context, in *ProbeOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WhoisInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WhoisBotService_ServiceDesc.Streams[0], WhoisBotService_ProbeHost_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProbeOptions, WhoisInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhoisBotService_ProbeHostClient = grpc.ServerStreamingClient[WhoisInfo]

// WhoisBotServiceServer is the server API for WhoisBotService service.
// All implementations should embed UnimplementedWhoisBotServiceServer
// for forward compatibility.
type WhoisBotServiceServer interface {
	// ProbeHost immediately starts whois query (manual use).
	// production use is limited due to system passing new tasks through redis queues
	ProbeHost(*ProbeOptions, grpc.ServerStreamingServer[WhoisInfo]) error
}

// UnimplementedWhoisBotServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhoisBotServiceServer struct{}

func (UnimplementedWhoisBotServiceServer) ProbeHost(*ProbeOptions, grpc.ServerStreamingServer[WhoisInfo]) error {
	return status.Errorf(codes.Unimplemented, "method ProbeHost not implemented")
}
func (UnimplementedWhoisBotServiceServer) testEmbeddedByValue() {}

// UnsafeWhoisBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhoisBotServiceServer will
// result in compilation errors.
type UnsafeWhoisBotServiceServer interface {
	mustEmbedUnimplementedWhoisBotServiceServer()
}

func RegisterWhoisBotServiceServer(s grpc.ServiceRegistrar, srv WhoisBotServiceServer) {
	// If the following call pancis, it indicates UnimplementedWhoisBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhoisBotService_ServiceDesc, srv)
}

func _WhoisBotService_ProbeHost_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProbeOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WhoisBotServiceServer).ProbeHost(m, &grpc.GenericServerStream[ProbeOptions, WhoisInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhoisBotService_ProbeHostServer = grpc.ServerStreamingServer[WhoisInfo]

// WhoisBotService_ServiceDesc is the grpc.ServiceDesc for WhoisBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhoisBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whois.v1.WhoisBotService",
	HandlerType: (*WhoisBotServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProbeHost",
			Handler:       _WhoisBotService_ProbeHost_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bots/v1/whois_bot.proto",
}
