// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: whois/v1/whois.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhoisProbeService_ProbeIP_FullMethodName = "/whois.v1.WhoisProbeService/ProbeIP"
)

// WhoisProbeServiceClient is the client API for WhoisProbeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhoisProbeServiceClient interface {
	ProbeIP(ctx context.Context, in *ProbeOptions, opts ...grpc.CallOption) (*WhoisInfo, error)
}

type whoisProbeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhoisProbeServiceClient(cc grpc.ClientConnInterface) WhoisProbeServiceClient {
	return &whoisProbeServiceClient{cc}
}

func (c *whoisProbeServiceClient) ProbeIP(ctx context.Context, in *ProbeOptions, opts ...grpc.CallOption) (*WhoisInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoisInfo)
	err := c.cc.Invoke(ctx, WhoisProbeService_ProbeIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhoisProbeServiceServer is the server API for WhoisProbeService service.
// All implementations should embed UnimplementedWhoisProbeServiceServer
// for forward compatibility.
type WhoisProbeServiceServer interface {
	ProbeIP(context.Context, *ProbeOptions) (*WhoisInfo, error)
}

// UnimplementedWhoisProbeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhoisProbeServiceServer struct{}

func (UnimplementedWhoisProbeServiceServer) ProbeIP(context.Context, *ProbeOptions) (*WhoisInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProbeIP not implemented")
}
func (UnimplementedWhoisProbeServiceServer) testEmbeddedByValue() {}

// UnsafeWhoisProbeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhoisProbeServiceServer will
// result in compilation errors.
type UnsafeWhoisProbeServiceServer interface {
	mustEmbedUnimplementedWhoisProbeServiceServer()
}

func RegisterWhoisProbeServiceServer(s grpc.ServiceRegistrar, srv WhoisProbeServiceServer) {
	// If the following call pancis, it indicates UnimplementedWhoisProbeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhoisProbeService_ServiceDesc, srv)
}

func _WhoisProbeService_ProbeIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhoisProbeServiceServer).ProbeIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhoisProbeService_ProbeIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhoisProbeServiceServer).ProbeIP(ctx, req.(*ProbeOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// WhoisProbeService_ServiceDesc is the grpc.ServiceDesc for WhoisProbeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhoisProbeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whois.v1.WhoisProbeService",
	HandlerType: (*WhoisProbeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProbeIP",
			Handler:    _WhoisProbeService_ProbeIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whois/v1/whois.proto",
}
