// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: node_manager/v1/bot_coordinator.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotCoordinatorService_Connect_FullMethodName = "/whois.v1.BotCoordinatorService/Connect"
)

// BotCoordinatorServiceClient is the client API for BotCoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotCoordinatorServiceClient interface {
	// Connect is used by bots to establish connection to coordinator server
	Connect(ctx context.Context, in *BotCredentials, opts ...grpc.CallOption) (*ConnectionInfo, error)
}

type botCoordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotCoordinatorServiceClient(cc grpc.ClientConnInterface) BotCoordinatorServiceClient {
	return &botCoordinatorServiceClient{cc}
}

func (c *botCoordinatorServiceClient) Connect(ctx context.Context, in *BotCredentials, opts ...grpc.CallOption) (*ConnectionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionInfo)
	err := c.cc.Invoke(ctx, BotCoordinatorService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotCoordinatorServiceServer is the server API for BotCoordinatorService service.
// All implementations should embed UnimplementedBotCoordinatorServiceServer
// for forward compatibility.
type BotCoordinatorServiceServer interface {
	// Connect is used by bots to establish connection to coordinator server
	Connect(context.Context, *BotCredentials) (*ConnectionInfo, error)
}

// UnimplementedBotCoordinatorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotCoordinatorServiceServer struct{}

func (UnimplementedBotCoordinatorServiceServer) Connect(context.Context, *BotCredentials) (*ConnectionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedBotCoordinatorServiceServer) testEmbeddedByValue() {}

// UnsafeBotCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotCoordinatorServiceServer will
// result in compilation errors.
type UnsafeBotCoordinatorServiceServer interface {
	mustEmbedUnimplementedBotCoordinatorServiceServer()
}

func RegisterBotCoordinatorServiceServer(s grpc.ServiceRegistrar, srv BotCoordinatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedBotCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotCoordinatorService_ServiceDesc, srv)
}

func _BotCoordinatorService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCoordinatorServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCoordinatorService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCoordinatorServiceServer).Connect(ctx, req.(*BotCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

// BotCoordinatorService_ServiceDesc is the grpc.ServiceDesc for BotCoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotCoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whois.v1.BotCoordinatorService",
	HandlerType: (*BotCoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _BotCoordinatorService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_manager/v1/bot_coordinator.proto",
}
